http:
  host: "![niJDIww7/2Q=]"
  port: "![Zt0zTqPYtlo=]"
  path: "![egSSG86ZKTFdQtfkdw/mEw==]"
  
salesforce:
  Username: "![k1kp2TEsqfocpEoS/v1mdgLOmiPmUwe8AWkqYW1hN3Y=]"
  Password: "![zun9ZZE5Lckyaf1xNZkAQQNM7mHadbY5]"
  Security: "![oaQynbxvmqhCYHWdYG7g0fudboZBBs7kNyJSmROgGfw=]"